version: "3.1"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  queue:
    image: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      - 1883:1883
